Fixed depoy command
Slash at the beginning causing:
error: invalid charm name "cs:/~natefinch/discourse"

Lowercase 'g' a the end causes:
error: invalid value "mem=2g" for flag --constraints: bad "mem" constraint: must be a non-negative float with optional M/G/T/P suffix